/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.dagger;

import javax.inject.Inject;

public class App {

    @Inject
    public String string;

    private void onCreate() {
        MyComponent component = DaggerMyComponent.create();
        component.inject(this);
    }

    public static void main(String[] args) {
        App app = new App();
        app.onCreate();
        System.out.println("App string = " + app.string);
    }
}
